name:
  ci-build

  # Run job only if:
  # - the commit is tagged starting with v
on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment

      - name: Run tests
        run: pnpm run test

  build-and-publish:
    needs: test

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      # Custom action to login to Docker Hub, build and push the Docker image
      - uses: ./.github/actions/build-and-publish
        with:
          docker-username: ${{ vars.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          docker-repository: ${{ vars.DOCKERHUB_REPO }}
