name: ci-dev

on:
  push:
    branches:
      - dev

jobs:
  get-short-sha:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.short-sha.outputs.sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: short-sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  ci-staging:
    # Reusable workflows are not called with uses inside a job's steps â€” they are called at the job level directly!
    needs: get-short-sha
    uses: ./.github/workflows/ci-shared.yml
    with:
      image-tag: dev-${{ needs.get-short-sha.outputs.sha }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
