name: publish-staging

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  get-short-sha:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.short-sha.outputs.sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get short SHA
        id: short-sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  code-quality:
    uses: ./.github/workflows/shared-quality.yml

  publish-staging:
    needs: [code-quality, get-short-sha]
    uses: ./.github/workflows/shared-docker.yml
    with:
      image-tag: dev-${{ needs.get-short-sha.outputs.sha }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
